<?php $_session = Mage::getSingleton('checkout/session'); ?>
<?php $_code=$this->getMethodCode() ?>
<?php if (Mage::getStoreConfig('buckaroo/buckaroo3extended_transfer/use_creditmanagement', Mage::app()->getStore()->getStoreId())): ?>
    <?php
    $name = $this->getName();
    $email = $this->getEmail();
    
    $gender = $this->getGender();
    $dob = $this->getDob();
    list($DD, $MM, $YYYY) = $dob;
    ?>
    <div id="payment-errors" class="validation-advice" style="display:none;"></div>
    <fieldset class="form-list">
        <ul id="payment_form_<?php echo $_code ?>" style="display:none" class="buckaroo3extended_input">
            <li>
                <label class="required"><?php echo $this->__('Salutation');?>: <em>*</em></label>
                <div class="input-box">  
                    <select name="<?php echo $_code;?>_BPE_Customergender" class="validate-select validate-number" id="<?php echo $_code;?>_BPE_Customergender" title="<?php echo $this->__('Salutation');?>">
	                    <option value=''><?php echo $this->__('Select'); ?></option>
	                    <option value="1" <?php echo ($this->getGender()===1)?'selected':'';?>><?php echo $this->__('Mr.'); ?></option>
	                    <option value="2" <?php echo ($this->getGender()===2)?'selected':'';?>><?php echo $this->__('Mrs.'); ?></option>
	                </select>
                </div>
            </li>
            <li>
                <label class="required"><?php echo $this->__('Name');?>:</label>
                <div class="input-box">
                    <span class="disabled" id="<?php echo $_code;?>_BPE_Customername"><?php echo $name; ?></span>
                </div>
            </li>
            <li>
                <label class="required" for="overschrijving:payment:month"><?php echo $this->__('Date of birth') ?>: <em>*</em></label>
                    <div class="input-box customer-dob overschrijving_customer-billing-dob" id="">
<?php 
$dateInputDD = <<< DATE_INPUT_DD
<div class="dob-day">
<input type="text" class="input-text" title="{$this->__('Day')}" value="{$DD}" name="{$_code}_customerbirthdate[day]" id="overschrijving:payment:day">
<label for="overschrijving:payment:day">{$this->__('DD')}</label>
</div>
DATE_INPUT_DD;

$dateInputMM = <<< DATE_INPUT_MM
<div class="dob-month">
<input type="text" class="input-text" title="{$this->__('Month')}" value="{$MM}" name="{$_code}_customerbirthdate[month]" id="overschrijving:payment:month">
<label for="overschrijving:payment:month">{$this->__('MM')}</label>
</div>
DATE_INPUT_MM;

$dateInputYYYY = <<< DATE_INPUT_YYYY
<div class="dob-year">
<input type="text" class="input-text" title="{$this->__('Year')}" value="{$YYYY}" name="{$_code}_customerbirthdate[year]" id="overschrijving:payment:year">
<label for="overschrijving:payment:year">{$this->__('YYYY')}</label>
</div>
DATE_INPUT_YYYY;

$strtr = array(
'%b' => '%1$s',
'%B' => '%1$s',
'%m' => '%1$s',
'%d' => '%2$s',
'%e' => '%2$s',
'%Y' => '%3$s',
'%y' => '%3$s'
);

$dateFormat = preg_replace('/[^\%\w]/', '\\1', Mage::app()->getLocale()->getDateStrFormat(Mage_Core_Model_Locale::FORMAT_TYPE_SHORT));

echo sprintf(strtr($dateFormat, $strtr), $dateInputMM, $dateInputDD, $dateInputYYYY);
?>
                        <div style="display:none;" class="dob-full">
                            <input type="hidden" name="<?php echo $_code;?>_payment[dob]" id="payment:dob">
                        </div>
                        <div style="display: none;" class="validation-advice"></div>
                    </div>
                    <script type="text/javascript">
                    //&lt;![CDATA[
                    var customer_dob = new Varien.DOB('.overschrijving_customer-billing-dob', true, '%d-%m-%y');
                    //]]&gt;
                    </script>
            </li>
            <li>
                <label class="required"><?php echo $this->__('E-mail address') ?>: <em>*</em></label>
                <div class="input-box">
                    <input class="input-text validate-email required-entry" type="text" title="<?php echo $this->__('E-mail address') ?>" name="<?php echo $_code ?>_BPE_Customermail" id="<?php echo $_code ?>_BPE_Customermail" value="<?php echo $email ?>" />
                </div>
            </li> 
            <li>
                <?php echo Mage::helper('buckaroo3extended')->__('Please make sure all fields are filled in correctly before proceeding.'); ?>
            </li>  
        </ul>
    </fieldset>
    
<?php else: ?>
    <div id="payment-errors" class="validation-advice" style="display:none;"></div>
    
    <fieldset class="form-list">
        <?php $_code = $this->getMethodCode() ?>
        <ul id="payment_form_<?php echo $_code ?>" style="display:none;">
            <li>
                <?php echo $this->__('You will receive an email with further payment instructions when you place your order.') ?>
            </li>
        </ul>
    </fieldset>
<?php endif; ?>