<div id="payment-errors" class="validation-advice" style="display:none;"></div>

<fieldset class="form-list">
    <?php $_code = $this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none;">
        <li>
            <?php echo Mage::helper('buckaroo3extended')->__('You will be redirected to our payment service provider to process your payment.') ?>
        </li>
    </ul>
</fieldset>
