<?php
$billing_info=Mage::getSingleton('checkout/session')->getQuote()->getBillingAddress();
$firstname=$billing_info->getFirstname();
$lastname=$billing_info->getLastname();
$email=$billing_info->getEmail();

$gender=(int)Mage::getSingleton('checkout/session')->getQuote()->getCustomerGender();
?>
<div id="payment-errors" class="validation-advice" style="display:none;"></div>

<?php $_code=$this->getMethodCode() ?>
<ul id="payment_form_<?php echo $_code ?>" style="display:none">    
    <li>
        <div class="input-box">
            <label><?php echo $this->__('Salutation') ?></label>
            <br>
            <select name="<?php echo $_code;?>_BPE_Customergender" class="validate-select">
            	<option value="1" <?php echo ($gender===1)?'selected':'';?>><?php echo $this->__('Mr.'); ?></option>
            	<option value="2" <?php echo ($gender===2)?'selected':'';?>><?php echo $this->__('Mrs.'); ?></option>
            </select>
        </div>
    </li>
    
    <li>
        <div class="input-box">
            <label><?php echo $this->__('First Name') ?> <span class="required">*</span></label>
            <br>
            <input class="input-text required-entry" type="input" name="<?php echo $_code;?>_BPE_Customerfirstname" value="<?php echo $firstname; ?>" />
        </div>
    </li>
    
    <li>
        <div class="input-box">
            <label><?php echo $this->__('Last Name') ?> <span class="required">*</span></label>
            <br>
            <input class="input-text required-entry" type="input" name="<?php echo $_code;?>_BPE_Customerlastname" value="<?php echo $lastname; ?>" />
        </div>
    </li>
    
    <li>
        <label><?php echo $this->__('E-mail') ?> <span class="required">*</span></label>
        <br>
        <div class="input-box">
        	<input class="input-text required-entry validate-email" type="input" name="<?php echo $_code;?>_BPE_Customermail" value="<?php echo $email; ?>" />
        </div>
    </li>
    
    <li>
        <?php echo $this->__('You will receive an email with further payment instructions when you place your order.') ?>
    </li>
</ul>



