<?php $_code=$this->getMethodCode() ?>

<div id="payment-errors" class="validation-advice" style="display:none;"></div>
<fieldset class="form-list">
    <ul id="payment_form_<?php echo $_code ?>" style="display:none" class="buckaroo3extended_input">
        <li>
            <?php echo Mage::helper('buckaroo3extended')->__('This information, combined with the information filled out in the billing information step, will be used for a credit check by Buckaroo Payment Services. Please make sure all fields are filled in correctly before proceeding.')?>
        </li>
        <li>
            <label class="required"><?php echo $this->__('Salutation');?>: <em>*</em></label>
            <div class="field field-set">  
                <select name="<?php echo $_code;?>_BPE_Customergender" class="validate-select validate-number">
                    <option value="1" <?php echo ($this->getGender()===1)?'selected':'';?>><?php echo $this->__('Mr.'); ?></option>
                    <option value="2" <?php echo ($this->getGender()===2)?'selected':'';?>><?php echo $this->__('Mrs.'); ?></option>
                </select>
                <span class="disabled"><?php echo $this->getName(); ?></span>
            </div>
        </li>
        <li>
            <label class="required"><?php echo $this->__('Bank account') ?>: <em>*</em></label>
            <div class="field">
                <input class="input-text required-entry" type="text" name="<?php echo $_code;?>_bpe_customer_account_number" value="<?php echo $this->getBankAccount(); ?>" />
            </div>
        </li>
        <li>
            <div class="field">
                <label class="required" for="payment:month"><?php echo $this->__('Date of Birth') ?>: <em>*</em></label>
                <div class="input-box customer-dob customer-billing-dob">
<?php $dob = $this->getDob(); ?>
<?php 
$dateInputDD = <<< DATE_INPUT_DD
<div class="dob-day">
 <input type="text" class="input-text validate-custom validation-over-18" title="{$this->__('Day')}" value="{$dob[0]}" name="{$_code}_customerbirthdate[day]" id="payment:day">
 <label for="payment:day">{$this->__('DD')}</label>
</div>
DATE_INPUT_DD;

$dateInputMM = <<< DATE_INPUT_MM
<div class="dob-month">
 <input type="text" class="input-text validate-custom" title="{$this->__('Month')}" value="{$dob[1]}" name="{$_code}_customerbirthdate[month]" id="payment:month">
 <label for="payment:month">{$this->__('MM')}</label>
</div>
DATE_INPUT_MM;

$dateInputYYYY = <<< DATE_INPUT_YYYY
<div class="dob-year">
    <input type="text" class="input-text validate-custom" title="{$this->__('Year')}" value="{$dob[2]}" name="{$_code}_customerbirthdate[year]" id="payment:year">
    <label for="payment:year">{$this->__('YYYY')}</label>
</div>
DATE_INPUT_YYYY;
                        
$strtr = array(
    '%b' => '%1$s',
    '%B' => '%1$s',
    '%m' => '%1$s',
    '%d' => '%2$s',
    '%e' => '%2$s',
    '%Y' => '%3$s',
    '%y' => '%3$s'
);
     
$dateFormat = preg_replace('/[^\%\w]/', '\\1', Mage::app()->getLocale()->getDateStrFormat(Mage_Core_Model_Locale::FORMAT_TYPE_SHORT));

echo sprintf(strtr($dateFormat, $strtr), $dateInputMM, $dateInputDD, $dateInputYYYY);
?>
                        <div style="display: none;" class="dob-full">
                         <input type="hidden" name="<?php echo $_code;?>_payment[dob]" id="payment:dob">
                        </div>
                    <div style="display: none;" class="validation-advice"></div>
                </div>
                <script type="text/javascript">
                //&lt;![CDATA[
                    var customer_dob = new Varien.DOB('.customer-billing-dob', true, '%d-%m-%y');
                //]]&gt;
                </script>
             </div>
        </li>   
    </ul>
</fieldset>