<div class="module-message warning">
    <h4><?php echo Mage::helper('buckaroo3extended')->__('These options are only intended for expert users. Tampering with the default settings may negatively affect the workflow and performance of all Buckaroo payment methods. Use at your own risk.')?></h4>
</div>
<script type="text/javascript" charset="utf-8" src="<?php echo $this->getSkinUrl("js/tig_buckaroo3extended/jquery-1.4.4.min.js");?>"></script>
<script type = 'text/javascript'>
jQuery.noConflict();
jQuery('document').ready(
	function() {
		if (jQuery("#buckaroo_buckaroo3extended_active").val() == 0 ) {
			jQuery("#buckaroo_buckaroo3extended").prev().prev().addClass('disabled');
		} 
		else if (jQuery("#buckaroo_buckaroo3extended_active").val() == 1 
				&& jQuery("#buckaroo_buckaroo3extended_mode").val() == 1)
		{
			jQuery("#buckaroo_buckaroo3extended").prev().prev().addClass('test');
		} 
		else
		{
			jQuery("#buckaroo_buckaroo3extended").prev().prev().addClass('live');
		}

    	jQuery('.buckaroo-header').html('&nbsp;').css('background-image', "url('<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>adminhtml/default/default/images/tig_buckaroo3extended/buckaroo_large.png')").css('width','151').css('height','30');

		<?php foreach($this->config as $config): ?>
			jQuery('#buckaroo_buckaroo3extended_<?php echo $config; ?>').prev().prev().addClass('advanced');
		<?php endforeach;?>
    	    									      
		<?php foreach($this->methods as $method):?>
    		if (jQuery("#buckaroo_buckaroo3extended_<?php echo $method; ?>_active").val() == 0 ) {
    			jQuery("#buckaroo_buckaroo3extended_<?php echo $method; ?>").prev().prev().addClass('disabled');
    		} 
    		else if (jQuery("#buckaroo_buckaroo3extended_<?php echo $method; ?>_active").val() == 1 
    				&& jQuery("#buckaroo_buckaroo3extended_<?php echo $method; ?>_mode").val() == 1)
    		{
    			jQuery("#buckaroo_buckaroo3extended_<?php echo $method; ?>").prev().prev().addClass('test');
    		} 
    		else
    		{
    			jQuery("#buckaroo_buckaroo3extended_<?php echo $method; ?>").prev().prev().addClass('live');
    		}
		<?php endforeach;?>
		<?php foreach($this->services as $service):?>    
    		if (jQuery("#buckaroo_buckaroo3extended_<?php echo $service; ?>_active").val() == 0 ) {
    			jQuery("#buckaroo_buckaroo3extended_<?php echo $service; ?>").prev().prev().addClass('disabled');
    		} 
    		else if (jQuery("#buckaroo_buckaroo3extended_<?php echo $service; ?>_active").val() == 1 
    				&& jQuery("#buckaroo_buckaroo3extended_<?php echo $service; ?>_allow_push").val() == 0)
    		{
    			jQuery("#buckaroo_buckaroo3extended_<?php echo $service; ?>").prev().prev().addClass('advanced');
    		} 
    		else
    		{
    			jQuery("#buckaroo_buckaroo3extended_<?php echo $service; ?>").prev().prev().addClass('advanced');
    		}
	    <?php endforeach;?>
    }
);
</script>