<?php if (!$this->getIsKlarnaEnabled()): ?>
    <?php return $this; ?>
<?php endif; ?>
<div class="error-msg buckaroo">
    <h4><?php echo Mage::helper('buckaroo3extended')->__('You have the Klarna Paymentmodule installed in your shop. Unfortunately the Buckaroo fee functionality does not work alongside this module. Therefore the Buckaroo fee functionality has been disabled. Please deactivate the Klarna module to use this functionality again.')?></h4>
</div>
<?php /* Stylesheet not available */ ?>
<style>
    .error-msg.buckaroo { margin-bottom:25px; padding:8px 8px 8px 32px; }
    .error-msg.buckaroo h4 { margin:0; }
</style>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/TIG/Buckaroo3Extended/klarnaCheck.js'); ?>"></script>
