<div style="
background-image:url('<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>adminhtml/default/default/buckaroo/images/buckaroo_large.png'); 
background-repeat:no-repeat; 
background-color:rgb(255,255,255); 
padding:5px;
padding-left:160px;
height:30px;
border:1px solid #CCCCCC;
background-position:5px 5px;
">
    <h4><?php echo Mage::helper('buckaroo3extended')->__('Looking for Buckaroo payment methods? We have our own tab to the left under Sales.')?></h4>
</div>