<?php
$version = Mage::getVersion();
$edition = Mage::getEdition();

if ($edition == 'Community' && version_compare($version, '1.7.2') == -1): ?>
<div class="error-msg buckaroo">
    <h4><?php echo Mage::helper('buckaroo3extended')->__('You have enabled PayPal Seller Protection. You have to warn your customer to fill in the region-field, otherwise the Seller Protection will not be applicable to PayPal.')
    ?></h4>
</div>
<?php /* Stylesheet not available */ ?>
<style>
    .error-msg.buckaroo { margin-bottom:25px; padding:8px 8px 8px 32px; }
    .error-msg.buckaroo h4 { margin:0; }
</style>
<?php return $this; ?>
<?php endif; ?>


<?php if($this->getIsRegionRequired()): ?>
    <?php return $this; ?>
<?php endif; ?>
<div class="error-msg buckaroo">
    <h4><?php echo Mage::helper('buckaroo3extended')->__('You have enabled PayPal Seller Protection. This feature requires Region with regard to the shipping address of the customer. Please select the specific countries to which PayPal is applicable for, and make the Regions required accordingly.') ?></h4>
</div>
<?php /* Stylesheet not available */ ?>
<style>
    .error-msg.buckaroo { margin-bottom:25px; padding:8px 8px 8px 32px; }
    .error-msg.buckaroo h4 { margin:0; }
</style>
