<?php $_helper = $this->helper('buckaroo3extended'); ?>
<tr>
    <td>
        <h2 class="content-heading"><?php echo $_helper->__('BPE 3.0 version');?> <?php echo Mage::getConfig()->getModuleConfig("TIG_Buckaroo3Extended")->version;?></h2>
        <table id="supportWrap" cellpadding="0" cellspacing="0">
            <tr>
                <td class="col-left">
                    <div class="text-box">
                        <h3><?php echo $_helper->__('Quick reference guide');?></h3>
                        <ol>
                            <li><strong><?php echo $_helper->__('Log in to the ');?> <a target="_blank" href="https://payment.buckaroo.nl/"><?php echo $_helper->__('Buckaroo Payment Plaza');?></a> <?php echo $_helper->__(' to collect the following security settings:');?></strong>
                                <ol>
                                    <li><?php echo $_helper->__('(Merchant) Key - Profile &rarr; Websites &rarr; Key.');?></li>
                                    <li><?php echo $_helper->__('Secret Key - Configuration &rarr; Secret key for Digitale signature &rarr; Secret Key.');?></li>
                                    <li><?php echo $_helper->__('Certificate - Configuration &rarr; Manage certificates (BPE 3.0).');?></li>
                                    <li><?php echo $_helper->__('Certificate Thumbprint - Configuration &rarr; Manage certificates (BPE 3.0).');?></li>
                                </ol>
                            </li>
                            <li><strong><?php echo $_helper->__('Upload the Certificate to the Magento database under the Certificate Management tab.');?></strong>
                                <ol>
                                    <li><?php echo $_helper->__('Give a name which is used for storing the certificate.');?></li>
                                    <li><?php echo $_helper->__('Select the certificate file to upload and Save Config.');?></li>
                                </ol>
                            </li>
                            <li><strong><?php echo $_helper->__('Enter the collected Merchant- &amp; Secret Key under the Base Configuration tab.');?></strong>
                                <ol>
                                    <li><?php echo $_helper->__('After adding the keys Save Config.');?></li>
                                    <li><?php echo $_helper->__('Select the uploaded certificate from the dropdown.');?></li>
                                    <li><?php echo $_helper->__('Add the corresponding thumbprint and Save Config.');?></li>
                                </ol>
                            </li>
                            <li><strong><?php echo $_helper->__('Configure and enable the individual payment methods.');?></strong>
                                <ol>
                                    <li><?php echo $_helper->__('Payment method specific settings are set under the corresponding tab.');?></li>
                                    <li><?php echo $_helper->__('Payment methods must be enabled within Buckaroo and Magento.');?></li>
                                    <li><?php echo $_helper->__('Contact Buckaroo support for activating or availale payment methods.');?></li>
                                </ol>
                            </li>
                            <li><strong><?php echo $_helper->__('Enable the module and select the Test or Live modus.');?></strong>
                                <ol>
                                   <li><?php echo $_helper->__('The module has many options to adapt to your business rules.');?></li>
                                   <li><?php echo $_helper->__('The manual gives more detailed information per subject.');?></li>
                                   <li><?php echo $_helper->__('The scope of the individual setting is presented as [GLOBAL], [WEBSITE] or [STOREVIEW].');?></li> 
                                </ol>
                            </li>
                        </ol>
                    </div> 
                    <div class="text-box">
                        <h3><?php echo $_helper->__('Legend');?></h3>
                            <ul id="legend">
                                <li class="disabled"><?php echo $_helper->__('Payment method - Disabled');?></li>
                                <li class="test"><?php echo $_helper->__('Payment method - Test Modus');?></li>
                                <li class="live"><?php echo $_helper->__('Payment method - Live Modus');?></li>
                                <li class="advanced"><?php echo $_helper->__('Advanced Configuration');?></li>
                            </ul>
                    </div>
                </td>
                
                <td class="col-faux"></td>
        
                <td class="col-right">
                    <div class="text-box">
                        <h3><?php echo $_helper->__('Magento &amp; 3rd party version compatibility');?></h3>
                        <ul>
                            <li><?php echo $_helper->__('Magento Community Edition version');?> 1.5, 1.6 &amp; 1.7</li>
                            <li><?php echo $_helper->__('Magento Enterprise Edition version');?> 1.11 &amp; 1.12</li>
                        </ul>
                        <ul>
                            <li><?php echo $_helper->__('OneStepCheckout version');?> 4.0.7</li>
                        </ul>
                    </div>
                    <div class="text-box">
                        <h3><?php echo $_helper->__('Support');?></h3>
                        <p><?php echo $_helper->__('The module is developed by Total Internet Group, commissioned by Buckaroo. Depending on the nature of the issue or question you should contact either Buckaroo or Total Internet Group.');?></p>
                        <h4><?php echo $_helper->__('Module basic configuration and account information');?></h4>
                        <p><?php echo $_helper->__('Acquire your (Merchant) key, Secret key, certificate and certificate thumbprint prior contacting Buckaroo technical support:');?></p>
                        <p><a href="http://www.buckaroo.nl" target="_blank"><img src="<?php echo $this->getSkinUrl('images/tig_buckaroo3extended/'); ?>buckaroo_small.png" alt="" /></a></p>
                        <table class="contact">
                             <tr>
                                <td class="first"><?php echo $_helper->__('Buckaroo Payment Plaza:');?></td>
                                <td class="last"><a target="_blank" href="https://payment.buckaroo.nl/">payment.buckaroo.nl</a></td>
                            </tr>
                            <tr>
                                <td class="first"><?php echo $_helper->__('Phone:');?></td>
                                <td class="last">+31(0)30-711 50 50</td>
                            </tr>
                            <tr>
                                <td class="first"><?php echo $_helper->__('E-mail:');?></td>
                                <td class="last"><a href="mailto:support@buckaroo.nl">support@buckaroo.nl</a></td>
                            </tr>
                        </table>
                        <h4><?php echo $_helper->__('Module support and advanced configuration');?></h4>
                        <p><?php echo $_helper->__('For configuration conflicts, bugs and Magento based support contact Total Internet Group:');?></p>
                        <p><a href="http://www.totalinternetgroup.nl" target="_blank"><img src="<?php echo $this->getSkinUrl('images/tig_buckaroo3extended/'); ?>tig_logo_medium.gif" alt="" /></a></p>
                        <table class="contact">
                             <tr>
                                <td class="first"><?php echo $_helper->__('Online support form:');?></td>
                                <td class="last"><a target="_blank" href="http://support.totalinternetgroup.nl/anonymous_requests/new">support.totalinternetgroup.nl</a></td>
                            </tr>
                            <tr>
                                <td class="first"><?php echo $_helper->__('E-mail:');?></td>
                                <td class="last"><a href="mailto:support@totalinternetgroup.nl">support@totalinternetgroup.nl</a></td>
                            </tr>
                            <tr>
                                <td class="first"><?php echo $_helper->__('Online Documentation');?></td>
                                <td class="last"><a target="_blank" href="http://www.totalinternetgroup.nl/support">www.totalinternetgroup.nl/support</a></td>
                            </tr>
                        </table>
                    </div>
                    <div class="text-box">
                        <h3><?php echo $_helper->__('Documentation');?></h3>
                        <p><?php echo $_helper->__('A list of documents regarding the module.');?></p>
                        <ul>
                            <li><a class="pdf" target="_blank" href="<?php echo $this->getSkinUrl('media/TIG/Buckaroo3Extended/manual.pdf')?>" title="<?php echo $_helper->__('Download a PDF format of the manual. Currently the manual is only available in Dutch.');?>"><?php echo $_helper->__('installation manual buckaroo bpe3 %s.pdf (NL)', 'v4.4.2.0');?></a></li>
                        </ul>
                    </div>
                </td>
            </tr>
        </table>
    </td>
</tr>