<div style="
background-image:url('<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>adminhtml/default/default/images/fam_bullet_error.gif');
background-repeat:no-repeat; 
background-color:rgb(255,255,255); 
padding:9px;
padding-left:28px;
height:27px;
border:1px solid #CCCCCC;
background-position:10px 10px;
">
    <h4><?php echo Mage::helper('buckaroo3extended')->__('You are using Buckaroo 3 Extended Payment Module version ') . Mage::getConfig()->getModuleConfig("TIG_Buckaroo3Extended")->version; ?></h4>
</div>