<?php
$billing_info=Mage::getSingleton('checkout/session')->getQuote()->getBillingAddress();
$firstname=$billing_info->getFirstname();
$lastname=$billing_info->getLastname();
$email=$billing_info->getEmail();

$gender=(int)Mage::getSingleton('checkout/session')->getQuote()->getCustomerGender();
?>
<div id="payment-errors" class="validation-advice" style="display:none;"></div>

<fieldset class="form-list">
    <?php $_code=$this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <?php echo $this->__('You will receive an email with further payment instructions when you place your order.') ?>
        </li>
        <li>
            <label><?php echo $this->__('Name') ?>:</label>
            <div class="input-box">
            	<div class="v-fix">
	           		<select name="<?php echo $_code;?>_BPE_Customergender" style="width:80px;" class = "validate-select">
	           			<option value="" <?php echo ($gender===0)?'selected':'';?>><?php echo $this->__('unknown'); ?></option>
	           			<option value="1" <?php echo ($gender===1)?'selected':'';?>><?php echo $this->__('Mr.'); ?></option>
	           			<option value="2" <?php echo ($gender===2)?'selected':'';?>><?php echo $this->__('Mrs.'); ?></option>
	           		</select>
            	</div>
     	   		<div class="v-fix">
           			&nbsp;<input class="input-text required-entry" type="input" name="<?php echo $_code;?>_BPE_Customerfirstname" value="<?php echo $firstname; ?>" style="width: 80px;" />
           		</div>
           		<div class = "v-fix">
           			&nbsp;<input class="input-text required-entry" type="input" name="<?php echo $_code;?>_BPE_Customerlastname" value="<?php echo $lastname; ?>" style="width: 81px;" />
           		</div>
           	</div>
        </li>
        <li>
            <label><?php echo $this->__('E-mail') ?>:</label>
            <div class="input-box">
            	<input class="input-text required-entry validate-email" type="input" name="<?php echo $_code;?>_BPE_Customermail" value="<?php echo $email; ?>" />
            </div>
        </li>
    </ul>
</fieldset>