<?php if ($this->getBuckarooFee()): ?>
    <?php $_displaySetting = $this->getFeeDisplaySetting(); ?>
    <?php if ($_displaySetting === 1): //excl tax?>
        <tr>
            <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
                <?php echo $this->getTotal()->getTitle() ?>
            </td>
            <td style="<?php echo $this->getStyle() ?>" class="a-right">
                <?php echo $this->helper('checkout')->formatPrice($this->getBuckarooFee()) ?>
            </td>
        </tr>
    <?php elseif($_displaySetting === 2): //incl tax?>
        <tr>
            <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
                <?php echo $this->getTotal()->getTitle() ?>
            </td>
            <td style="<?php echo $this->getStyle() ?>" class="a-right">
                <?php echo $this->helper('checkout')->formatPrice($this->getBuckarooFee() + $this->getBuckarooFeeTax()) ?>
            </td>
        </tr>
    <?php else: //both?>
        <tr>
            <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
                <?php echo $this->getTotal()->getTitle() . Mage::helper('buckaroo3extended')->__(' (Excl. Tax)'); ?>
            </td>
            <td style="<?php echo $this->getStyle() ?>" class="a-right">
                <?php echo $this->helper('checkout')->formatPrice($this->getBuckarooFee()) ?>
            </td>
        </tr>
        <tr>
            <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
                <?php echo $this->getTotal()->getTitle() . Mage::helper('buckaroo3extended')->__(' (Incl. Tax)'); ?>
            </td>
            <td style="<?php echo $this->getStyle() ?>" class="a-right">
                <?php echo $this->helper('checkout')->formatPrice($this->getBuckarooFee() + $this->getBuckarooFeeTax()) ?>
            </td>
        </tr>
    <?php endif; ?>
<?php endif; ?>