<div id="payment-errors" class="validation-advice" style="display:none;"></div>

<fieldset class="form-list">
    <?php $_code=$this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <label><?php echo $this->__('Accountnumber') ?>:</label>
            <div class="input-box">
            	<input class="input-text required-entry" type="input" name="<?php echo $_code;?>_BPE_Accountnumber" value="" />
            </div>
        </li>
    </ul>
</fieldset>