<?php $_session = Mage::getSingleton('checkout/session'); ?>
<?php $_code=$this->getMethodCode() ?>
<?php
$billing_info=Mage::getSingleton('checkout/session')->getQuote()->getBillingAddress();
$firstname=$billing_info->getFirstname();
$lastname=$billing_info->getLastname();
$email=$billing_info->getEmail();

$gender=(int)Mage::getSingleton('checkout/session')->getQuote()->getCustomerGender();
$gender = $gender ? $gender : (int) $_session->getData($_code . '_BPE_Customergender');
?>
<?php $firstname = $_session->getData($_code . '_BPE_Customerfirstname') ? $_session->getData($_code . '_BPE_Customerfirstname') : $firstname; ?>
<?php $lastname = $_session->getData($_code . '_BPE_Customerlastname') ? $_session->getData($_code . '_BPE_Customerlastname') : $lastname; ?>
<?php $email = $_session->getData($_code . '_BPE_Customermail') ? $_session->getData($_code . '_BPE_Customermail') : $email; ?>
<?php $_session = Mage::getSingleton('checkout/session'); ?>
<div id="payment-errors" class="validation-advice" style="display:none;"></div>

<fieldset class="form-list">
    <ul id="payment_form_<?php echo $_code ?>" style="display:none" class="buckaroo3extended_input">
        <li>
            <label class="required"><?php echo $this->__('Salutation') ?>: <em>*</em></label>
            <div class="input-box">
           		<select name="<?php echo $_code;?>_BPE_Customergender" class="validate-select validate-number" id="<?php echo $_code;?>_BPE_Customergender" title="<?php echo $this->__('Salutation');?>">
                    <option value=''><?php echo $this->__('Select'); ?></option>
                    <option value="1" <?php echo ($this->getGender()===1)?'selected':'';?>><?php echo $this->__('Mr.'); ?></option>
                    <option value="2" <?php echo ($this->getGender()===2)?'selected':'';?>><?php echo $this->__('Mrs.'); ?></option>
                </select>
           	</div>
        </li>
        <li>
            <label class="required"><?php echo $this->__('First name') ?>: <em>*</em></label>
            <div class="input-box">
                <input class="input-text required-entry" type="input" title="<?php echo $this->__('First name') ?>" name="<?php echo $_code;?>_BPE_Customerfirstname" value="<?php echo $firstname; ?>" id="<?php echo $_code;?>_BPE_Customerfirstname"/>
            </div>
        </li>
       	<li>
       	    <label class="required"><?php echo $this->__('Last name') ?>: <em>*</em></label>
       	    <div class="input-box">
                <input class="input-text required-entry" type="input" title="<?php echo $this->__('Last name') ?>" name="<?php echo $_code;?>_BPE_Customerlastname" value="<?php echo $lastname; ?>" id="<?php echo $_code;?>_BPE_Customerlastname"/>
           	</div>
        </li>
        <li>
            <label class="required"><?php echo $this->__('E-mail address') ?>: <em>*</em></label>
            <div class="input-box">
            	<input class="input-text required-entry validate-email" type="input" title="<?php echo $this->__('E-mail address') ?>" name="<?php echo $_code;?>_BPE_Customermail" value="<?php echo $email; ?>" id="<?php echo $_code;?>_BPE_Customermail"/>
            </div>
        </li>
        <li>
            <?php echo $this->__('You will receive an email with further payment instructions when you place your order.') ?>
        </li>
    </ul>
</fieldset>