<script type="text/javascript">
    oldFirstname = '';
    oldLastname = '';
    oldGender = '';
    oldDay = '';
    oldMonth = '';
    oldYear = '';
    jQuery("#billing\\:firstname").change(
        function() {
            firstname = jQuery(this).val();
            
            if (!jQuery('#buckaroo3extended_onlinegiro_BPE_Customerfirstname').val() || jQuery('#buckaroo3extended_onlinegiro_BPE_Customerfirstname').val() == oldFirstname) {
                jQuery('#buckaroo3extended_onlinegiro_BPE_Customerfirstname').val(firstname);
                sendData(jQuery('#buckaroo3extended_onlinegiro_BPE_Customerfirstname'));
            }
            
            if (!jQuery('#buckaroo3extended_payperemail_BPE_Customerfirstname').val() || jQuery('#buckaroo3extended_payperemail_BPE_Customerfirstname').val() == oldFirstname) {
                jQuery('#buckaroo3extended_payperemail_BPE_Customerfirstname').val(firstname);
                sendData(jQuery('#buckaroo3extended_payperemail_BPE_Customerfirstname'));
            }
            
            jQuery('#buckaroo3extended_paymentguarantee_BPE_Customername').html(
                firstname + ' ' + jQuery("#billing\\:lastname").val()
            );
            
            jQuery('#buckaroo3extended_transfer_BPE_Customername').html(
                firstname + ' ' + jQuery("#billing\\:lastname").val()
            );
            
            jQuery('#buckaroo3extended_directdebit_account_owner').val(
                firstname + ' ' + jQuery("#billing\\:lastname").val()
            );
            
            jQuery('#buckaroo3extended_empayment_BPE_Accountholder').val(
                firstname + ' ' + jQuery("#billing\\:lastname").val()
            );
            
            oldFirstname = firstname;
        }
    );
    jQuery("#billing\\:lastname").change(
        function() {
            lastname = jQuery(this).val();
            
            if (!jQuery('#buckaroo3extended_onlinegiro_BPE_Customerlastname').val() || jQuery('#buckaroo3extended_onlinegiro_BPE_Customerlastname').val() == oldLastname) {
                jQuery('#buckaroo3extended_onlinegiro_BPE_Customerlastname').val(lastname);
                sendData(jQuery('#buckaroo3extended_onlinegiro_BPE_Customerlastname'));
            }
            
            if (!jQuery('#buckaroo3extended_payperemail_BPE_Customerlastname').val() || jQuery('#buckaroo3extended_payperemail_BPE_Customerlastname').val() == oldLastname) {
                jQuery('#buckaroo3extended_payperemail_BPE_Customerlastname').val(lastname);
                sendData(jQuery('#buckaroo3extended_payperemail_BPE_Customerlastname'));
            }
            
            jQuery('#buckaroo3extended_paymentguarantee_BPE_Customername').html(
                jQuery("#billing\\:firstname").val() + ' ' + lastname
            );
            
            jQuery('#buckaroo3extended_transfer_BPE_Customername').html(
                jQuery("#billing\\:firstname").val() + ' ' + lastname
            );
            
            jQuery('#buckaroo3extended_directdebit_account_owner').val(
                jQuery("#billing\\:firstname").val() + ' ' + lastname
            );
            
            jQuery('#buckaroo3extended_empayment_BPE_Accountholder').val(
                jQuery("#billing\\:firstname").val() + ' ' + lastname
            );
            
            oldLastname = lastname;
        }
    );
    jQuery("#billing\\:gender").change(
    	function() {
    		gender = jQuery("#billing\\:gender option:selected").val();
    		
    		if (
    			!jQuery("#buckaroo3extended_paymentguarantee_BPE_Customergender option:selected").val()
    			|| jQuery("#buckaroo3extended_paymentguarantee_BPE_Customergender option:selected").val() == oldGender
    		) {
    			jQuery("#buckaroo3extended_paymentguarantee_BPE_Customergender option[value='" + gender + "']").attr('selected', 'selected');
    		}
    		
    		if (
    			!jQuery("#buckaroo3extended_onlinegiro_BPE_Customergender option:selected").val()
    			|| jQuery("#buckaroo3extended_onlinegiro_BPE_Customergender option:selected").val() == oldGender
    		) {
    			jQuery("#buckaroo3extended_onlinegiro_BPE_Customergender option[value='" + gender + "']").attr('selected', 'selected');
    		}
    		
    		oldGender = gender;
    	}
    );
    jQuery("#billing\\:day").change(
    	function() {
    		day = jQuery(this).val();
            
            if (!jQuery("#container_payment_method_buckaroo3extended_paymentguarantee #payment\\:day").val() || jQuery("#container_payment_method_buckaroo3extended_paymentguarantee #payment\\:day").val() == oldDay) {
                jQuery("#container_payment_method_buckaroo3extended_paymentguarantee #payment\\:day").val(day);
                sendData(jQuery("#container_payment_method_buckaroo3extended_paymentguarantee #payment\\:day"));
            }
    		
    		oldDay = day;
    	}
    );
    jQuery("#billing\\:month").change(
    	function() {
    		month = jQuery(this).val();
            
            if (!jQuery("#container_payment_method_buckaroo3extended_paymentguarantee #payment\\:month").val() || jQuery("#container_payment_method_buckaroo3extended_paymentguarantee #payment\\:month").val() == oldMonth) {
                jQuery("#container_payment_method_buckaroo3extended_paymentguarantee #payment\\:month").val(month);
                sendData(jQuery("#container_payment_method_buckaroo3extended_paymentguarantee #payment\\:month"));
            }
    		
    		oldMonth = month;
    	}
    );
    jQuery("#billing\\:year").change(
    	function() {
    		year = jQuery(this).val();
            
            if (!jQuery("#container_payment_method_buckaroo3extended_paymentguarantee #payment\\:year").val() || jQuery("#container_payment_method_buckaroo3extended_paymentguarantee #payment\\:year").val() == oldYear) {
                jQuery("#container_payment_method_buckaroo3extended_paymentguarantee #payment\\:year").val(year);
                sendData(jQuery("#container_payment_method_buckaroo3extended_paymentguarantee #payment\\:year"));
            }
    		
    		oldYear = year;
    	}
    );
</script>
