<![if !lt IE 9]>
<script type="text/javascript">
function sendData(element)
{
     jQuery.post(
         '<?php echo $this->getUrl('buckaroo3extended/checkout/saveData');?>',
         {
             name: element.attr('name'),
             value: element.val()
         }
     );
}
</script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/TIG/Buckaroo3Extended/saveData.js'); ?>"></script>
<![endif]>