<div id="payment-errors" class="validation-advice" style="display:none;"></div>

<fieldset class="form-list buckaroo-method">
    <?php $_code=$this->getMethodCode() ?>
	<ul class="form-list" id="payment_form_<?php echo $_code; ?>" style="display:none;" class="buckaroo3extended_input">
        <li>
            <label for="<?php echo $_code ?>_account_owner" class="required"><?php echo $this->__('Bank account holder') ?>:<em>*</em></label>
            <div class="input-box">
                <input type="text" title="<?php echo $this->__('Bank account holder') ?>" class="input-text required-entry" id="<?php echo $_code ?>_account_owner" name="payment[account_owner]" value="<?php echo $this->getAccountOwner(); ?>" />
            </div>
        </li>
        <li>
            <label for="<?php echo $_code ?>_account_number" class="required"><?php echo $this->__('Bank account number') ?>:<em>*</em></label>
            <div class="input-box">
                <input type="text" title="<?php echo $this->__('Bank account number') ?>" class="input-text required-entry" id="<?php echo $_code ?>_account_number" name="payment[account_number]" value="<?php echo $this->getAccountNumber(); ?>" />
            </div>
        </li>
        <li>
            <label for="<?php echo $_code ?>_bank_number" class="required"><?php echo $this->__('BIC number') ?>:<em>*</em></label>
            <div class="input-box">
                <input type="text" title="<?php echo Mage::helper('buckaroo3extended')->__('BIC number') ?>" class="input-text required-entry" id="<?php echo $_code ?>_bank_number" name="payment[bank_number]" value="<?php echo $this->getBankNumber(); ?>" />
            </div>
        </li>
        <li>
            <?php 
                $ibanConverterLink = '<a target="_blank" href="https://iban.buckaroo.nl/">'.Mage::helper('buckaroo3extended')->__('here').'</a>';
                echo Mage::helper('buckaroo3extended')->__('Convert your account number to IBAN %s',$ibanConverterLink);
            ?>
        </li>
        <li>
			<?php echo Mage::helper('buckaroo3extended')->__("Please enter these fields as they appear on your bank account.") ?>
		</li>
	</ul>
</fieldset>