<div id="payment-errors" class="validation-advice" style="display:none;"></div>

<fieldset class="form-list">
    <?php $_code=$this->getMethodCode() ?>
	<ul class="form-list" id="payment_form_<?php echo $_code; ?>" style="display:none;" class="buckaroo3extended_input">
		<li>
			<?php echo Mage::helper('buckaroo3extended')->__("Please enter these fields as they appear on your bankaccount.") ?>
		</li>
        <li>
            <label for="<?php echo $_code ?>_account_owner" class="required"><?php echo $this->__('Account name') ?>: <em>*</em></label>
            <div class="input-box">
                <input type="text" title="<?php echo $this->__('Account name') ?>" class="input-text required-entry" id="<?php echo $_code ?>_account_owner" name="payment[account_owner]" value="<?php echo $this->getAccountOwner(); ?>" />
            </div>
        </li>
        <li>
            <label for="<?php echo $_code ?>_account_number" class="required"><?php echo $this->__('Account number') ?>: <em>*</em></label>
            <div class="input-box">
                <input type="text" title="<?php echo $this->__('Account number') ?>" class="input-text required-entry" id="<?php echo $_code ?>_account_number" name="payment[account_number]" value="<?php echo $this->getAccountNumber(); ?>" />
            </div>
        </li>
	</ul>
</fieldset>
